// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2wseascRcbhPmzc9AaK3NWD2SXx8mcM',
    appId: '1:846060285496:web:e269fe2a8514bc2afa80cd',
    messagingSenderId: '846060285496',
    projectId: 'app-simple-movie-recomendation',
    authDomain: 'app-simple-movie-recomendation.firebaseapp.com',
    storageBucket: 'app-simple-movie-recomendation.firebasestorage.app',
    measurementId: 'G-X44D4KRT2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_r5XWGbYP1HusHrO04jUmCmbP98FoFa8',
    appId: '1:846060285496:android:0775b39d95811c8bfa80cd',
    messagingSenderId: '846060285496',
    projectId: 'app-simple-movie-recomendation',
    storageBucket: 'app-simple-movie-recomendation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-QRtSIcrkJY4RLJRLawKf16ay7F48Q4',
    appId: '1:846060285496:ios:ddef75adb8aa3f72fa80cd',
    messagingSenderId: '846060285496',
    projectId: 'app-simple-movie-recomendation',
    storageBucket: 'app-simple-movie-recomendation.firebasestorage.app',
    iosBundleId: 'com.example.amflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0-QRtSIcrkJY4RLJRLawKf16ay7F48Q4',
    appId: '1:846060285496:ios:ddef75adb8aa3f72fa80cd',
    messagingSenderId: '846060285496',
    projectId: 'app-simple-movie-recomendation',
    storageBucket: 'app-simple-movie-recomendation.firebasestorage.app',
    iosBundleId: 'com.example.amflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2wseascRcbhPmzc9AaK3NWD2SXx8mcM',
    appId: '1:846060285496:web:47910e509bc3ca55fa80cd',
    messagingSenderId: '846060285496',
    projectId: 'app-simple-movie-recomendation',
    authDomain: 'app-simple-movie-recomendation.firebaseapp.com',
    storageBucket: 'app-simple-movie-recomendation.firebasestorage.app',
    measurementId: 'G-M7TCQVL564',
  );
}
